src/components/common/Input/InputComment.jsx, src/components/common/Input/input.css, src/components/common/Modal/AlertModal.jsx, src/components/common/Modal/AlertModal.module.css, src/components/common/TabMenu/TabMenu.jsx, src/components/common/TabMenu/TabMenu.module.css, src/styles/global.css, src/styles/reset.css
- 공통 컴포넌트 추가
- 삭제모달, 하단 nav바, 댓글 입력 컴포넌트 마크업 및 디자인
- global.css, reset.css 수정됨
closed: #11
=> 💄 [design] 공통 요소 중 삭제 모달, 하단 nav, 댓글 입력 컴포넌트 마크업 및 디자인 #11

src/components/common/Modal/IconProductModal.jsx, src/components/common/Modal/IconProductModal.module.css, src/components/common/Modal/PostModal.jsx, src/components/common/Modal/PostModal.module.css
- 공통 UI 컴포넌트 중 포스트 모달 마크업 및 스타일 작업
- 공통 UI 컴포넌트 중 상품 모달 마크업 및 스타일 작업
closed: #15
=> [💄design] 공통 요소 중 포스트 모달, 상품 모달 마크업 및 디자인#15

src/pages/Login/LoginMain/LoginMain.jsx, src/pages/Login/LoginMain/LoginMain.module.css
- images 폴더에 kakao.png 추가 
closed: #17
=> [design] 이메일 회원가입 기능 추가 #17

src/pages/Login/LoginEmail/LoginEmail.jsx, src/pages/Login/LoginEmail/LoginEmail.module.css
- [x ] 폴더, 파일 등 업로드
- LoginEmail.jsx, css 파일 추가 했습니다. 
closed: #23
=> [design] LoginEmail Page 마크업 추가 했습니다! #23

src/pages/Splash/Splash.jsx, src/pages/Splash/Splash.module.css
- pages/Splash 폴더 내 Splash.jsx, Splash.module.css 추가
closed: #18
=> [design] Splash UI 작업 #18

src/pages/Profile/Followers.jsx, src/pages/Profile/Followers.module.css
=> [💄design] 팔로워페이지 마크업 #21

src/pages/Product/AddProduct.jsx, src/pages/Product/AddProduct.module.css
- [x ] 폴더, 파일 등 업로드
- addProduct. jsx, css 추가
- images 폴더에 눈물.png 추가(삭제해도 됨)
closed: #25
=> [design] feat/add product 마크업 추가 /#25

src/pages/Join/JoinEmail/JoinEmail.jsx, src/pages/Join/JoinEmail/JoinEmail.module.css
- src /pages/join 에 joinEmail 마크업 추가
closed: #31
=> [💄(css) design] join page 마크업 추가 #31

src/components/Common/User/User.module.css, src/components/Common/User/UserFollow/UserFollow.jsx, src/components/Common/User/UserSearch/UserSearch.jsx, src/pages/SearchUser/SearchUser.jsx, src/pages/SearchUser/SearchUser.module.css
- [ x] 폴더, 파일 등 업로드
-SearchUser.jsx, css 파일 추가
closed: #33
=> [design] Feat/search- page 마크업 추가/#33

src/pages/Profile/Followers.jsx
- class 두개 이상인 태그 코드 수정
closed: #44
=> [🎨style] 팔로워페이지 class 수정 #44

src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx, src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
-page/join/ join profile setting page 폴더에 마크업 추가
closed: #37
=> [💄(css) design] join profile setting page 마크업 추가

src/pages/ProfileModification/ProfileModification.jsx, src/pages/ProfileModification/ProfileModification.module.css
- src /pages/profileModification 파일에 마크업 추가
closed: #47
=> [💄(css) design] profileModification 마크업추가

src/App.js
=> [feat] 코드 라우팅 기능 추가

src/pages/Chat/ChatRoom/ChatRoom.jsx, src/pages/Chat/ChatRoom/ChatRoom.module.css
=> [💄design] chat room 마크업#54

src/pages/Profile/ProductList.jsx, src/pages/Profile/ProductList.module.css, src/pages/Profile/YourProfile.jsx, src/pages/Profile/YourProfile.module.css
- YourProfile 페이지 마크업 완료
closed: #41
=> [design] Your Profile 마크업 추가 #41

src/components/Common/Post/Post.jsx, src/components/Common/Post/Post.module.css, src/components/Common/Product/Product.jsx, src/components/Common/Product/Product.module.css, src/components/Common/Profile/ProfilePost.jsx, src/components/Common/Profile/ProfilePost.module.css, src/components/Common/Profile/UserProfile.jsx, src/components/Common/Profile/UserProfile.module.css, src/components/common/Profile/ProfileProduct.jsx, src/components/common/Profile/ProfileProduct.module.css
- [] 기능 추가
- Feed, MyProfile 페이지에서 중복되는 부분 컴포넌트로 분리
closed: #62
=> [refactor] Feed, MyProfile 페이지 컴포넌트로 분리

src/utils/baseUrl.js
- [x ] 폴더, 파일 등 업로드
- [  ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- src/ api 폴더에 api js파일 분리해서 넣음 (안에 api는 별도로 추가해야함)
- 해당 폴더 내 더미 파일 삭제
- utils 폴더에 base url 파일 추가함
closed: #63
=> [add] API 파일과 utils 폴더에 base url 파일 추가

src/components/Common/Chat/ChatItem.jsx, src/components/Common/Chat/ChatItem.module.css, src/components/Common/User/UserSearch/UserSearch.jsx, src/pages/Chat/ChatList/ChatList.jsx, src/pages/Chat/ChatList/ChatList.module.css
- 채팅리스트 컴포넌트 분리 후 마크업 추가
closed: #50
=> [💄(css) design] 채팅 리스트 마크업 추가

src/components/layout/Layout.jsx, src/pages/Chat/ChatList/ChatList.jsx, src/pages/Chat/ChatList/ChatList.module.css
- 채팅리스트 페이지 레아아웃 틀에 맞춰서 코드 수정
- 채팅리스트 중복 css 삭제
closed: #50
=> [🎨 style] 채팅리스트페이지 레이아웃 폼에 맞춰 수정

package-lock.json, package.json, src/pages/Join/JoinEmail/JoinEmail.jsx, src/pages/Join/JoinEmail/JoinEmail.module.css
- 유효성 검토 및 에러시 에러 안내 문구 추가(api연결해야지 이메일 중복 검토 가능)
- react-hook-form 설치
closed: #31
=> [✨ feat] 회원가입 페이지 유효성 검토 및 라이브러리 설치 #31

src/components/common/Profile/ProfilePost.module.css, src/pages/Post/PostDetail.module.css
- [] 기능 추가
- padding, width 수정
closed: #67
=> [style] Post 관련 컴포넌트 padding, width 수정 #67

src/App.js, src/components/common/HeaderTest/Header.jsx, src/components/common/HeaderTest/Header.module.css, src/components/common/User/User.module.css, src/components/common/User/UserSearch/UserSearch.jsx, src/components/layout/Layout.jsx, src/pages/Product/ProductModi.jsx, src/pages/Product/ProductModi.module.css, src/pages/SearchUser/SearchUser.jsx, src/pages/SearchUser/SearchUser.module.css
- SearchUser 레이아웃 교체
- Addproduct 레이아웃 교체
- ProductModi 추가
closed: #61
=> [style] 레이아웃 변경 #61

src/components/common/Profile/ProfilePost.module.css
- Post 컴포넌트 padding 수정
closed: #67
=> [style] Post 컴포넌트 padding 수정 #67

src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx, src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
- 페이아웃 폼 사용해서 적용 및 input 값 css 적용
- 유효성검토 부분 api 적용 후 확인 필요
closed: #37
=> [🎨 style] 프로필 설정페이지 레이아웃 css및 input 값 css 적용

src/components/common/HeaderTest/Header.jsx, src/components/common/Input/Input.jsx, src/components/layout/Layout.jsx, src/pages/Chat/ChatRoom/ChatRoom.jsx, src/pages/Chat/ChatRoom/ChatRoom.module.css, src/pages/Upload/Upload.jsx
=> [💄design] 레이아웃 Followers,Upload,ChatRoom 재수정 #85

src/components/layout/Layout.jsx, src/pages/ProfileModification/ProfileModification.jsx, src/pages/ProfileModification/ProfileModification.module.css
- 프로필 수정페이지 레이아웃 적용
closed: #47
=> [🎨 style] 프로필 수정페이지 레이아웃 적용 #47

src/components/common/HeaderTest/Header.module.css
- Header style placeholder 추가 
closed: #61
=> [style] Header 코드 추가 #61

src/App.js, src/pages/Login/LoginMain/LoginMain.jsx, src/pages/Login/LoginMain/LoginMain.module.css
- 라우터 path 아래와 같이 수정
- 수정함에 따라 `login/email` path가 사라져서 LoginMain.jsx에서 "이메일로 로그인하기" 클릭하면 LoginEmail.jsx가 렌더링되도록 로직 추가
----
- `/login`
- `/join`
- `/profile`
- `/`
- `/search`
- `/profile`
- `/m`
- `/followers`
- `/{userid}`
- `/product`
- `/m`
- `/post`
- `/upload`
- `/chat`
- `/{chatid}`
closed: #3
=> [refator] 라우터 수정, LoginMain에서 LoginEmail 조건부 렌더링 로직 추가 #92

src/pages/ProfileModification/ProfileModification.jsx, src/pages/ProfileModification/ProfileModification.module.css
- input 위아래 패딩 추가
- input title 소개입력 => 소개
closed: #47
=> [🎨 style]input 위아래 패딩 추가 및 오타 수정 #47

src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx, src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
- input요소에 패딩 추가 
-  '소개입력 ⇒ 소개'로 오타 수정
closed: #37
=> [🎨 style] input 패딩 추가 및 '소개입력 ⇒ 소개'로 오타 수정 # 37

src/pages/Join/JoinEmail/JoinEmail.jsx, src/pages/Join/JoinEmail/JoinEmail.module.css
- input요소 위아래 패딩 추가
-  에러 메시지 왼쪽 정렬
closed: #31
=> [🎨 style] input 패딩 추가 및 에러메시지 왼쪽 정렬 #31

src/components/common/Profile/ProfilePost.jsx, src/components/common/Profile/ProfilePost.module.css, src/pages/Feed/Feed.jsx, src/pages/Post/PostDetail.jsx, src/pages/Profile/MyProfile/MyProfile.jsx
- 프로필 페이지에서 리스트로 보기, 앨범으로 보기 버튼에 따라 포스트가 보여질 수 있도록 기능 추가
- 공통 컴포넌트 ProfilePost.jsx에서 페이지마다 각각 간격 설정
closed: #97
=> [feat] 프로필 페이지에서 리스트 또는 앨범으로 보기 버튼에 기능 추가, 공통 컴포넌트 ProfilePost.jsx 간격 수정 #97

src/components/common/Comment/Comment.jsx, src/components/common/Comment/Comment.module.css, src/components/common/HeaderTest/Header.jsx, src/components/common/HeaderTest/Header.module.css, src/components/common/TabMenu/TabMenu.jsx, src/components/common/TabMenu/TabMenu.module.css, src/components/layout/Layout.jsx
- 피드페이지에서 사용하는 HomeSearch 헤더 Input요소에서 h1 요소로 변경
- footerType이 none일 경우에, 빈 Footer 태그도 return 되지 않도록 수정
- footer에 border 추가
- post 페이지 댓글 폰트 스타일 수정
- 레이아웃 컴포넌트에서 사용하는 pathname 케이스 수정
closed: #102
=> [design] 공통 컴포넌트 레이아웃(헤더, 푸터) 수정 #102

src/components/layout/Layout.jsx, src/pages/Login/LoginEmail/LoginEmail.jsx, src/pages/Login/LoginEmail/LoginEmail.module.css
=> [feat] login 기능구현 #108

src/api/userAPI.js, src/components/layout/Layout.jsx, src/pages/Join/JoinEmail/JoinEmail.jsx
- 회원가입 input요소 포커스 아웃시 유효성 검사 
- user api checkAcountValid -> chdeckemailValid로 이메일 확인 api 변동
closed: #100
=> [🎨 style] 회원가입 input요소 포커스 아웃시 유효성 검사 가능하게 코드 수정 #100

src/components/common/Chat/ChatItem.module.css
- chatItem 제목 폰트 굵기 500으로 변경
closed: #50
=> [🎨 style] chatItem 제목 폰트 굵기 500으로 변경 #50

src/components/common/HeaderTest/Header.jsx, src/pages/Product/AddProduct.jsx, src/pages/Product/AddProduct.module.css
- AddProduct 페이지 기능구현
closed: #114
=> [feat] product 페이지 기능 구현

src/components/common/HeaderTest/Header.jsx, src/components/layout/Layout.jsx, src/pages/Product/AddProduct.jsx, src/pages/Product/AddProduct.module.css
- Addproduct 기능 추가 
closed: #114
=> [feat] product 페이지 기능구현 #114

src/api/imageAPI.js, src/api/userAPI.js, src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx, src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
- 이미지 받아서 미리보기 해주고 api 연동해서 데이터 값 저장
closed: #111
=> [✨ feat] 회원가입 프로필 설정 페이지 api 연동 완료 #111

src/pages/Product/AddProduct.jsx
- AddProduct 페이지 기능 수정 
closed: #114
=> [style] AddProduct 페이지 코드 수정#114

src/App.js, src/api/commentAPI.js, src/api/postAPI.js, src/api/productAPI.js, src/api/profileAPI.js, src/components/common/Comment/Comment.jsx, src/components/common/HeaderTest/Header.jsx, src/components/common/Post/Post.jsx, src/components/common/Post/Post.module.css, src/components/common/Product/Product.jsx, src/components/common/Product/Product.module.css, src/components/common/Profile/ProfilePost.jsx, src/components/common/Profile/ProfileProduct.jsx, src/components/common/Profile/UserProfile.jsx, src/components/common/Profile/UserProfile.module.css, src/components/layout/Layout.jsx, src/pages/Post/PostDetail.jsx
- 프로필, 게시글 상세페이지 라우터 수정
- 게시글 상세 페이지 API 연결
- 상세 페이지 내 게시글 정보 노출
- 댓글 API 연결 
- 게시글 상단에 작성자 영역 클릭 시 , 해당 계정 프로필 페이지로 이동하는 기능 추가
closed: #117
=> [feat] 게시글 상세 페이지 API 연결, 라우터 수정 #117

src/pages/Login/LoginEmail/LoginEmail.jsx, src/pages/Product/AddProduct.jsx
- AddProduct 수정
- loginEmail  loaclStorage accountname 추가 
closed: #114
=> [style] Addproduct 수정 /#114

src/components/common/HeaderTest/Header.jsx, src/components/common/Profile/ProfilePost.jsx, src/components/common/Profile/ProfileProduct.jsx, src/components/common/Profile/UserProfile.jsx, src/pages/Feed/Feed.jsx, src/pages/Post/PostDetail.jsx, src/pages/Splash/Splash.module.css
- 토큰이 필요한 페이지마다 로컬 스토리지에서 token, useraccount 가져오도록 코드 추가
- Splash 화면 연결
closed: #124
=> [feat] 로컬스토리지에서 저장된 토큰 가져오도록 코드 추가 및 Splash 화면 연결 #124

src/components/common/Chat/ChatItem.jsx, src/components/common/Chat/ChatItem.module.css, src/pages/Chat/ChatList/ChatList.module.css
- 마크업 추가
- navigate 기능 추가 
closed: #128
=> [feat] chat 마크업 및 기능추가 #128

src/components/layout/Layout.jsx, src/pages/Profile/Followers.jsx, src/pages/Profile/Followers.module.css
=> [✨feat]Followers API 연동 및 버튼 구현

src/pages/Feed/Feed.jsx, src/pages/Feed/FeedNone.jsx, src/pages/Feed/FeedNone.module.css, src/pages/Splash/Splash.module.css
- 로그인 유무에 따라 Splash 화면 후 렌더링 되는 화면이 다름
- 로그인을 하지 않은 경우 : 로그인 화면
- 로그인이 되어 있는 경우 : 같이 드실? 피드
closed: #127
=> [feat] 로그인 유무에 따라 페이지가 렌더링 되는 기능 추가 #127

src/components/common/Post/Post.jsx
-  게시글이 나타나는 모든 페이지에 해당합니다.
-  게시글 하단에는 하트 모양에 좋아요 버튼이 있습니다.
-  빈 하트를 클릭하면 색이 칠해진 하트로 변하고, 색이 칠해진 하트를 누르면 빈 하트로 변합니다.
-  좋아요 기능은 구현하지 않습니다.
- 좋아요 개수는 카운트 되어 하트모양 우측에 표시됩니다.
closed: #132
=> [feat] 좋아요 기능 구현 #132

src/components/common/Profile/OtherProfile.jsx, src/components/common/Profile/OtherProfile.module.css, src/components/common/Profile/ProfilePost.jsx, src/components/common/Profile/ProfileProduct.jsx, src/components/common/Profile/ProfileProduct.module.css, src/pages/Profile/YourProfile.jsx
=> [feat] 유저 프로필 API 연결 #134

src/components/common/HeaderTest/Header.jsx, src/components/common/Profile/OtherProfile.jsx, src/components/common/Profile/OtherProfile.module.css, src/components/layout/Layout.jsx
- 유저 팔로우 기능 추가
- API 연동 완료
closed: #134
=> [feat] 유저 프로필 팔로우 기능 추가 #134

src/pages/Product/AddProduct.jsx
- [ x ] 버그 수정
- AddProduct 기능 수정
closed: #114
=> [style] AddProduct 기능 수정 #114

src/api/profileAPI2.js, src/components/layout/Layout.jsx, src/context/AuthContext.jsx, src/index.js, src/pages/ProfileModification/ProfileModification.jsx, src/pages/ProfileModification/ProfileModification.module.css
- profileAPI2 생성해서 연결함 (추후 api 파일 병합 필요)
- 프로필 수정 페이지 api 연동해서 입력값 수정해서 api 서버로 보내고 리렌더링 완료
closed: #121
=> [✨ feat] 프로필 수정페이지 api 연동해서 수정 기능 구현 #121

src/api/followAPI.js, src/pages/Profile/Followers.jsx, src/pages/Profile/Followers.module.css, src/pages/Profile/MyProfile/Followings.jsx
-팔로잉 리스트 api 가져와서 나를 팔로우 한 정보 보여주는 기능 구현 완료
- 상대방 프로필 사진 보여줘야해서 img태그 추가와 css 추가
closed: #105
=> [feat] 팔로잉 리스트 api 연동 완료 및 기능구현 완료 #105

src/pages/Product/AddProduct.jsx
-AddProduct 코드 수정 했습니다. 
- https://emart.ssg.com/item/itemView.ssg?itemId=2097001396520&siteNo=6001&salestrNo=2449 이런 url 추가 했을 떄 생기는 오류 수정 
closed: #114
=> [style] AddProduct 코드 수정 

src/pages/Profile/Followers.jsx
- [] 기능 추가
-  const [buttonStates, setButtonStates] = useState([]) 버튼 상태 객체에서 배열로 변경
closed: #105
=> [fix] 팔로우 버튼 동시 변경되는 버그 수정 #105

src/App.js, src/components/common/Profile/OtherProfile.jsx, src/components/common/Profile/UserProfile.jsx
- 팔로잉 페이지 라우터 추가
- 프로필에서 팔로잉 클릭 시 팔로잉 페이지로 연결되는 코드 추가 
closed: #143
=> [feat] 팔로잉 페이지 라우터 추가 및 프로필에서 팔로잉 클릭 시 팔로잉 페이지로 연결되는 기능 추가

package-lock.json, package.json, src/components/common/HeaderTest/Header.module.css, src/components/layout/Layout.jsx, src/pages/Upload/Upload.jsx, src/pages/Upload/Upload.module.css
- 게시글 작성 기능 추가
- API 연동
closed: #118
=> [✨feat] 게시물 작성 기능 추가 #118

src/components/common/HeaderTest/Header.jsx, src/components/common/HeaderTest/Header.module.css, src/components/common/Input/Input.module.css, src/components/layout/Layout.module.css
- 헤더 검색 버튼 클릭 시 검색 페이지로 이동하는 코드 추가
- 쓸모없는 body 스타일 제거, Layout 컴포넌트에 공통으로 적용
closed: #149
=> [feat] 헤더 검색 버튼 클릭 시, 검색 페이지로 이동하는 코드 추가 #149

src/pages/Join/JoinEmail/JoinEmail.jsx, src/pages/Join/JoinEmail/JoinEmail.module.css
- 유효성 문제 없을시 버튼 바로 활성화
- css 전체 레이아웃에서 패딩값줘서 간격 띄움, input 간격 조정 폰트 사이즈 조정
closed: #111
=> [fix] 로그인페이지 유효성 검토 후 바로 버튼 활성화 수정 및 css 간격 조정 #111

src/components/common/User/User.module.css, src/components/common/User/UserSearch/UserSearch.jsx, src/pages/Login/LoginEmail/LoginEmail.jsx, src/pages/Login/LoginEmail/LoginEmail.module.css, src/pages/Login/LoginMain/LoginMain.module.css, src/pages/Product/AddProduct.jsx, src/pages/Product/AddProduct.module.css
- Product, Search, Login 파일 수정 
closed: #152
=> [style] product, search,login 코드 수정

src/pages/Product/AddProduct.module.css
- [x ] 버그 수정
-Product margin 값 변경 
closed: #152
=> [style] Product margin 값 변경 

src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx, src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
- 프로필 설정페이지 폰트 및 간격 조정
- 유효성 검사 완료 되면 버튼 바로 활성화 되도록 수정
- 회원가입 프로필 설정 페이지 id 중복검사 오류 수정
closed: #111
=> [fix] 회원가입 프로필 설정페이지 계정 Id 중복 검사 오류 수정 #111

src/pages/ProfileModification/ProfileModification.jsx, src/pages/ProfileModification/ProfileModification.module.css
- 프로필 수정 페이지 보더 레드와 메세지뜨는걸로 수정
closed: #121
=> [🐛 fix] 프로필 수정페이지 오류메세지 안뜨는 오류 수정 #121

src/pages/Login/LoginEmail/LoginEmail.module.css
=> [style] Login font color 수정 

src/pages/Product/AddProduct.module.css
- product 에러 color 변경
closed: #152
=> [style] product 에러 color 변경 

src/components/common/Post/Post.jsx, src/components/common/Post/Post.module.css, src/components/layout/Layout.jsx, src/pages/Chat/ChatRoom/ChatRoom.jsx
- 게시글 일정 값 너비 설정하여 말줄임 효과 추가
- 게시글 하단 게시글 작성일자 표현 방식 수정 
- 더보기 버튼 svg태그 삭제 후 background로 수정
closed: #164
=> [fix] 게시글 일정 값에 말줄임 효과 추가하는 스타일 추가, 게시글 작성 일자 표현 방식 수정 #164

src/pages/Upload/Upload.jsx, src/pages/Upload/Upload.module.css
=> [🎨style]게시글 작성페이지 수정 #148

src/pages/Upload/Upload.jsx
- 게시글 업로드 시 전달되는 날짜 데이터 수정되어 전달합니다.
closed: #170
=> [feat] 게시글 업로드 시 전달되는 날짜 데이터 수정 #170

src/components/common/Modal/AlertModal.module.css
- Confirm 모달 위치 수정하여 화면 가운데에 위치합니다
closed: #172
=> [fix] Confirm 모달 위치 수정 #172

package-lock.json, package.json, src/components/common/HeaderTest/Header.jsx, src/components/common/HeaderTest/Header.module.css, src/components/common/Post/Post.jsx, src/components/common/Profile/ProfilePost.jsx, src/components/common/User/User.module.css, src/components/common/User/UserFollow/UserFollow.jsx, src/components/common/User/UserSearch/UserSearch.jsx, src/components/common/User/UserSearch/UserSearch.module.css, src/components/layout/Layout.jsx, src/pages/SearchUser/SearchUser.jsx, src/pages/SearchUser/SearchUser.module.css
- 검색 페이지 및 공통 컴포넌트 마크업 수정
- 검색 기능 추가
closed: #178
=> [feat] 검색 기능 추가 #178

src/api/postAPI.js, src/api/productAPI.js, src/api/profileAPI.js, src/components/common/Profile/OtherProfile.jsx, src/components/common/Profile/ProfilePost.jsx, src/components/common/Profile/ProfileProduct.jsx
- 프로필 페이지(공통)
- 공구중인 사품 API 코드 분리 및 리팩토링
- 게시글 API 코드 분리 및 리팩토링
- YourProfile 페이지
- 유저 정보 API 코드 분리 및 리팩토링
- 팔로우/언팔로우 기능 API 코드 분리 및 리팩토링
closed: #187
=> 프로필 페이지 API 코드 분리 및 리팩토링 #187

src/components/common/Profile/OtherProfile.jsx
- 프로필 페이지에서 팔로우 버튼 클릭 할 때 전체 UI가 렌더링 되지 않고 버튼 UI만 바뀜
closed: #191
=> [fix] 프로필 페이지에서 팔로우 버튼 클릭할 때마다, 전체 UI가 렌더링 되는 이슈 수정 #191

package-lock.json, package.json, src/components/common/Modal/AlertModal/AlertModal.jsx, src/components/common/Modal/AlertModal/AlertModal.module.css, src/components/common/Profile/OtherProfile.jsx, src/pages/Profile/YourProfile/YourProfile.jsx
- 좌측 채팅 버튼: 해당 사용자와 채팅 페이지로 이동함
- 우측 공유 버튼: 클릭하면 해당 페이지 링크를 클립보드에 저장한 후, "클립보드에 복사되었습니다" Confirm 모달이 나타남
- 클립보드 라이브러리: react-copy-to-clipboard
closed: #193
=> [feat] YourProfile 페이지에서 사용자 정보 하단에 위치한 버튼 기능 추가 #193

src/api/commentAPI.js, src/components/common/Comment/Comment.module.css, src/components/common/Input/Input.jsx, src/components/common/Input/Input.module.css, src/components/layout/Layout.jsx, src/pages/Post/PostDetail.jsx, src/pages/Post/PostDetail.module.css
- 댓글 리스트 API 코드 리팩토링
- 푸터에 보더 추가
- 공통요소 Comment UI 수정
- 이미지 크기
- 텍스트 간격
- 댓글 등록 가능
- API 연동
- 댓글 입력 후 바로 페이지에서 확인 가능
- 오래된 댓글이 위로 올라갈 수 있도록 정렬하는 코드 추가
closed: #195
=> [feat] 상세페이지에서 댓글 입력 기능 추가, 기존 API 코드 리팩토링, 댓글 관련 UI 수정

src/api/commentAPI.js, src/api/profileAPI.js, src/components/common/Comment/Comment.jsx, src/components/common/Comment/Comment.module.css, src/components/common/Input/Input.jsx, src/components/common/Input/Input.module.css, src/components/common/Modal/AlertModal/AlertModal.jsx, src/components/common/Modal/Modal.jsx, src/pages/Post/PostDetail.jsx
- 내가 올린 댓글은 삭제 가능
- 댓글 우측 상단에 위치한 더보기 버튼을 누르면 삭제하기 메뉴가 담긴 모달이 나타남
- 삭제하기를 클릭하면, 삭제하겠습니까? 확인 모달이 나타남
- 확인을 클릭하면 댓글은 삭제됨.
- 취소를 클릭하면 모든 모달이 닫힘.
- 다른 사용자가 올린 댓글은 신고 가능
- 댓글 우측 상단에 위치한 더보기 버튼을 누르면 신고하기 메뉴가 담긴 모달이 나타남
- 신고하기를 클릭하면, 신고 API 가 실행되고, 신고 후 바로 "신고되었습니다." 확인 모달이 나타남.
- 댓글 입력칸 좌측에 프로필 사진이 나의 프로필 사진으로 변경됨.
- 내 프로필 정보 가져오는 API 코드 수정(profileAPI) => 이부분은 추후에 공통 정보로 빼도 좋을 듯
closed: #198
=> [feat] 댓글 삭제, 신고 기능 추가

src/components/common/Modal/AlertModal/AlertModal.jsx, src/components/common/Modal/AlertModal/AlertModal.module.css, src/pages/Upload/Upload.jsx, src/pages/Upload/Upload.module.css
- 모달창 배경 opacity 수정
closed: #183
=> [✨ feat] 게시물 업로드 아이템들 수정 #183

src/api/postAPI.js, src/components/common/Modal/Modal.jsx
- postAPI.js에 게시글 신고 API 코드 추가
- Modal.jsx에 게시글 신고 버튼 클릭 이벤트 추가
- 게시글 신고 기능 
closed: #210
=> [feat] 게시글 신고하기 기능 추가(API) #210

src/App.js, src/api/productAPI.js, src/components/common/Modal/Modal.jsx, src/components/common/Product/Product.jsx, src/components/layout/Layout.jsx, src/pages/Product/ProductModi.jsx, src/pages/Product/ProductModi.module.css
- ProductModi 파일 
closed: #215
=> [✨ feat] ProductModi 수정기능 추가 #215

src/pages/Upload/Upload.jsx, src/pages/Upload/Upload.module.css
- profile화면으로 데이터를 넘겨서 화면에 보여줌.
- 카카오지도 API를 이용하여 이용자의 현재장소를 띄워줌.
closed: #205
=> [✨feat] 데이터 넘기기 오류 수정, 위치API연결 #205

src/components/common/Chat/ChatItem.jsx, src/components/common/Chat/ChatItem.module.css, src/pages/Chat/ChatList/ChatList.jsx, src/pages/Chat/ChatList/ChatList.module.css
- 팔로잉api 연동해서 팔로잉한 사람 대화리스트에 뜨게 바꿈 
- 알림표시, 포인터 마크업 수정
closed: #220
=> [✨feat] 채팅리스트 리팩토링(api연동 및 마크업수정)

src/pages/ProfileModification/ProfileModification.jsx
=> [♻️ refactor] 프로필 수정페이지 주석 및 컨벤션 고침 #223

src/pages/ProfileModification/ProfileModification.jsx
- 계정ID 수정하다가 본래 ID로 해도 중복ID로 나오는 오류 수정
closed: #223
=> [fix] 계정 ID 중복검사 오류 수정(현재 userIId 도 중복검사 오류로 뜨는거 수정) #223

src/components/common/Product/Product.module.css
- 공구 중인 상품의 이름이 길어지면, 말줄임으로 표시
- 
closed: #238
=> [design] 공구 중인 상품의 이름이 길어지면 말줄임 스타일 추가 #238

src/api/mapAPI.js, src/api/uploadAPI.js, src/pages/Upload/Upload.jsx
- Upload페이지에서 사용된 API 분리
closed: #231
=> [♻️refactor] Upload페이지 api 분리 #231

src/api/productAPI.js, src/pages/Product/ProductModi.jsx
- ProductModi 파일 쉼표 기능 추가
closed: #215
=> [feat]쉼표 기능 추가 #215

src/pages/Product/ProductModi.module.css
- css background 제거 
closed: #242
=> [🎨 style] ProductModi css 변경 #242

src/pages/Product/ProductModi.jsx
- [v] 버그 수정
- src 폴더 및 파일 생성
closed: #244
=> [🐛 fix]ProductModi 오류 수정

src/pages/Follow/Followers/Followers.jsx
- 팔로워페이지 맞팔여부에 따라 삭제, 팔로우 버튼으로 나뉘는 기능 추가
- 팔로워페이지 팔로우버튼 클릭시 팔로워에 추가 되는 기능 추가
- 팔로워 페이지 언팔 기능 추가 및 버튼 반응 구현
- 팔로워페이지 버튼 삭제에서 취소로 변경
- 
closed: #206
=> [✨] follow페이지 취소, 팔로우 기능 구현/#206

src/pages/Login/LoginEmail/LoginEmail.jsx, src/pages/Login/LoginMain/LoginMain.jsx, src/pages/Product/AddProduct.jsx, src/pages/Product/ProductModi.jsx
=> [♻️ refactor] 컨벤션 적용 코드 #246

src/pages/Chat/ChatList/ChatList.jsx
- 채팅리스트 맞팔기준으로 리스트업 수정
closed: #220
=> [♻️ refacto] 채팅리스트 맞팔기준으로 리스트업하도록 수정 / #220

src/components/common/Chat/ChatItem.jsx
- 필요없는 변수 및 주석 삭제
closed: #220
=> [♻️ refactor] Feat/chat/chat list/ 페이지 필요없는 주석 및 변수 삭제 #220

src/api/imagesAPI.js, src/pages/Upload/Upload.jsx
=> [✨ feat] Upload페이지의 이미지 API 연동 및 분리 #233

src/components/common/Modal/AlertModal/AlertModal.jsx, src/components/common/Modal/AlertModal/AlertModal.module.css, src/components/common/Modal/Modal.jsx, src/pages/Chat/ChatRoom/ChatRoom.jsx, src/pages/Chat/ChatRoom/ChatRoom.module.css
- 채팅방 나가기 모달 및 나가기 기능 구현 
closed: #207
=> [✨feat] 채팅방 나가기 기능 구현#207

src/components/common/Profile/ProfilePost.jsx
- 앨범형으로 보기 클릭 시, 첫번째 이미지가 보이도록 수정
closed: #258
=> [fix] 앨범형으로 보기 클릭 시, 첫번째 이미지가 보이도록 수정 #258

src/pages/Join/JoinEmail/JoinEmail.jsx, src/pages/Join/JoinEmail/JoinEmail.module.css
- 로그인 회원가입 페이지 확대시 레이아웃 가운데 정렬
- 예외 처리  /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/ 추가
closed: #196
=> [♻️ refactor] join 페이지 리팩토링#196

src/pages/Product/ProductModi.jsx, src/pages/Product/ProductModi.module.css
- 초기화면에 인풋 밸류 삭제시 버튼 활성화 비활성화 버그 수정
closed: #261
=> [🐛 fix] ProductModi 버튼 활성화 수정 #261

src/api/profileAPI.js, src/components/common/Profile/UserProfile.jsx, src/pages/Profile/MyProfile/MyProfile.jsx
- 부모 요소에서 토큰을 전달받을 수 있도록 수정
closed: #264
=> [fix] 로그아웃 후 다른 계정으로 로그인 시, 프로필 페이지에서 이전 계정의 유저 정보가 보이는 이슈

src/components/common/Post/Post.jsx
- 게시글 내 컨텐츠 유무에 따른 margin 조정 #266
closed: #266
=> [design] 게시글 내 컨텐츠 유무에 따른 margin 조정 #266

src/components/common/Post/Post.jsx
- 이미지 리스트 생성하는 코드의 조건을 type을 확인하여 생성하는 것으로 조건문 수정하여 이슈 해결
closed: #268
=> [fix] 프로필 페이지 split 에러 #268

src/components/common/Header/Header.jsx
=> [🐛 fix] Productmodi button type 변경 #273

src/pages/Join/JoinProfileSetting/JoinProfileSetting.module.css
=> [fix] 회원가입프로필설정 페이지 레이아웃 중앙정렬로 맞춤 #196

src/pages/Follow/Followings/Followings.jsx
- 팔로잉페이지 언팔가눙 해당계정만 삭제하도록 수정
closed: #280
=> [fix] 팔로잉 언팔 해당계정만 삭제하도록 수정 #280
